### ISSUE TITLE
sesame-rio-api classload conflicts with Fedora 3.8.x

### ISSUE THREAD

**Issue by sprater** [Smithsonian/trippi-sparql#25]
I ran into a Tomcat classloader conflict when installing trippi-sparql in Fedora 3.8.1 (running under Tomcat 8.0.29).  I installed it on four identical hosts;  the install worked fine on three of the hosts, but failed on the fourth.

When I would try to retrieve an object from Fedora, the following exception would be thrown:

```
[...]
Caused by: java.lang.NoSuchMethodError: org.openrdf.rio.rdfxml.RDFXMLParser.getParserConfig()Lorg/openrdf/rio/ParserConfig;
        at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:278) ~[sesame-rio-rdfxml-2.7.11.jar:na]
        at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:233) ~[sesame-rio-rdfxml-2.7.11.jar:na]
        at org.trippi.io.SimpleParsingContext.<init>(SimpleParsingContext.java:56) ~[trippi-sparql-1.1.jar:na]
        at org.trippi.io.SimpleParsingContext.parse(SimpleParsingContext.java:116) ~[trippi-sparql-1.1.jar:na]
        at org.trippi.io.TripleIteratorFactory.getSimpleTriples(TripleIteratorFactory.java:79) ~[trippi-sparql-1.1.jar:na]
        at org.trippi.io.TripleIteratorFactory.allAsSet(TripleIteratorFactory.java:128) ~[trippi-sparql-1.1.jar:na]
        at org.fcrepo.server.storage.RDFRelationshipReader.readRelationships(RDFRelationshipReader.java:41) ~[fcrepo-server-3.8.1.jar:na]
        at org.fcrepo.server.storage.RDFRelationshipReader.readRelationships(RDFRelationshipReader.java:32) ~[fcrepo-server-3.8.1.jar:na]
[...]
```
After much comparing of environments and jar files, I finally tracked it down to a classloading discrepancy that appears to stem from duplicate classes in trippi-sparql-1.1 and Fedora's sesame-rio-api-2.7.11 jars.

On a functioning host, the RDFParser class is loaded from the Fedora sesame-rio-api jar:
```
[Loaded org.openrdf.rio.RDFParser from file:webapps/fedora/WEB-INF/lib/sesame-rio-api-2.7.11.jar]
```
On the broken host, the same class is loaded from the trippi-sparql jar:
```
[Loaded org.openrdf.rio.RDFParser from file:webapps/fedora/WEB-INF/lib/trippi-sparql-1.1.jar]
```
As a workaround, I exploded the sesame-rio-api-2.7.11.jar into webapps/fedora/WEB-INF/classes, in order to force Tomcat to load the sesame classes first (per the default class loading rules described in https://tomcat.apache.org/tomcat-8.0-doc/class-loader-howto.html), and the problem disappeared.

The problem can be reproduced by exploding the RDFParserBase class in the trippi-sparql jar into webapps/fedora/WEB-INF/classes, forcing it to be picked up, then restarting tomcat:
```
cd webapps/fedora/WEB-INF/classes
jar xvf ../lib/trippi-sparql-1.1.jar org/openrdf/rio/helpers/RDFParserBase.class
```
I'm not sure what the fix is;  not bundle the sesame-rio-api jar in trippi-sparql?  This bug is especially gruesome, in that there's no way of knowing which jar Tomcat will prefer to get the class from.

**Comment by ajs6f** [comment]
Oh, that's annoying. Okay, let me take a look at the dependency tree. I might-probably be able to exclude the library in question from the packaged artifact, depending on where it is coming from.

**Comment by ajs6f** [comment]
Looks like a simple exclusion should do the trick-- a PR will be available soon.

**Comment by sprater** [comment]
Thanks, @ajs6f.  When there's a branch I can test, I'll pull it down, build it, and confirm the fix.

**Comment by ajs6f** [comment]
Thanks, @sprater -- give [this one](https://github.com/Smithsonian/trippi-sparql/pull/26) a shot.

**Comment by sprater** [comment]
Yes, @ajs6f, that one fixes the problem.  Thanks for the quick turnaround!

**Comment by ajs6f** [comment]
Thanks for the awesome issue report! I'll leave this open until we can make a release, which shouldn't be too long.

**Comment by ajs6f** [comment]
The PR is now in `master`, but as mentioned, I will leave this open until we cut a release. That (hopefully) will be sometime next week.

**Comment by sprater** [comment]
Since it's spring cleaning time, shall we close and put this ticket out on the curb, too?

**Comment by ajs6f** [comment]
Boy, you are on a rampage, @sprater, flinging tickets over the side like Blackbeard. Okay, this one can go too!
