### ISSUE TITLE
Max connections quickly exceeded

### ISSUE THREAD

**Issue by whikloj** [Smithsonian/trippi-sparql#9]
This may not be an issue with the connector, but I wondered about setting both the maxTotal and maxDefaultPerRoute to the [same setting](https://github.com/Smithsonian/trippi-sparql/blob/master/trippi-sparql/src/main/java/edu/si/trippi/impl/sparql/SparqlConnector.java#L181-L182). 

I had left `<param name="maxHttpConnections" value="10">` at 10 and started getting exceptions, so I bumped it to 10,000 and started to get exceptions (within a couple minutes). This could also be due to Islandora's design in the Tuque layer. Mulgara had an unlimited pool size, is there such an option with this?

**Comment by ddavis** [comment]
I wonder if Jetty and/or JVM settings will have an effect on the limit for max connections?  How are you running Fuseki?

--
Dan

On 11/30/2016 02:12 PM, Jared Whiklo wrote:

This may not be an issue with the connector, but I wondered about setting both the maxTotal and maxDefaultPerRoute to the same setting<https://github.com/Smithsonian/trippi-sparql/blob/master/trippi-sparql/src/main/java/edu/si/trippi/impl/sparql/SparqlConnector.java#L181-L182>.

I had left <param name="maxHttpConnections" value="10"> at 10 and started getting exceptions, so I bumped it to 10,000 and started to get exceptions (within a couple minutes). This could also be due to Islandora's design in the Tuque layer. Mulgara had an unlimited pool size, is there such an option with this?

**Comment by whikloj** [comment]
I'm actually using Blazegraph which is also on the Tomcat container running Fedora.

**Comment by whikloj** [comment]
I do some recursive queries on the triplestore to get related item information, this is currently using the Fedora RISearch interface, perhaps I should try to get away from using that.

**Comment by ddavis** [comment]
Understood.  I am using the RISearch interface only for Islandora operations.  Any bespoke operations (mostly from Camel or HTTP services) are calling the Fuseki endpoints directly via HTTP.

--
Dan

On 11/30/2016 02:23 PM, Jared Whiklo wrote:

I do some recursive queries on the triplestore to get related item information, this is currently using the Fedora RISearch interface, perhaps I should try to get away from using that.

**Comment by ddavis** [comment]
Not fully true.  I am running via Islandora some Drush scripts.  But the queries are not terribly challenging and perhaps the largest result set of 13,000.

--
Dan

On 11/30/2016 02:29 PM, Davis, Daniel wrote:
Understood.  I am using the RISearch interface only for Islandora operations.  Any bespoke operations (mostly from Camel or HTTP services) are calling the Fuseki endpoints directly via HTTP.

--
Dan

On 11/30/2016 02:23 PM, Jared Whiklo wrote:

I do some recursive queries on the triplestore to get related item information, this is currently using the Fedora RISearch interface, perhaps I should try to get away from using that.

**Comment by whikloj** [comment]
Sorry I guess I wasn't clear. This error is occurring at the Fedora level.
```
ERROR 2016-11-30 13:02:18.234 [http-bio-8080-exec-19] (RISearchServlet) Unexpected error servicing API-A request
org.trippi.TrippiException: Maximum triplestore connections exceeded.
        at org.trippi.impl.base.ConcurrentTriplestoreReader.findTuples(ConcurrentTriplestoreReader.java:78) ~[trippi-core-1.5.10.jar:na]
        at org.fcrepo.server.resourceIndex.ResourceIndexImpl.findTuples(ResourceIndexImpl.java:297) ~[fcrepo-server-3.8.1.jar:na]
        at org.fcrepo.server.resourceIndex.ResourceIndexModule.findTuples(ResourceIndexModule.java:324) ~[fcrepo-server-3.8.1.jar:na]
        at org.trippi.server.TrippiServer.find(TrippiServer.java:118) ~[trippi-core-1.5.10.jar:na]
        at org.fcrepo.server.access.RISearchServlet.doFind(RISearchServlet.java:375) [fcrepo-server-3.8.1.jar:na]
        at org.fcrepo.server.access.RISearchServlet.doSearch(RISearchServlet.java:255) [fcrepo-server-3.8.1.jar:na]
        at org.fcrepo.server.access.RISearchServlet.doGet(RISearchServlet.java:204) [fcrepo-server-3.8.1.jar:na]
        at org.fcrepo.server.access.RISearchServlet.doGet(RISearchServlet.java:121) [fcrepo-server-3.8.1.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620) [servlet-api.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.55]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.55]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:369) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.fcrepo.server.security.jaas.AuthFilterJAAS.doFilter(AuthFilterJAAS.java:329) [fcrepo-security-jaas-3.8.1.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381) [spring-security-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
```

**Comment by ajs6f** [comment]
That doesn't seem to have anything to do with `trippi-sparql` (as evidenced by the complete absence of `edu.si` package names in that stacktrace). Have you been able to execute these query patterns in the _absence_ of `trippi-sparql`?

**Comment by whikloj** [comment]
@ajs6f I have never seen this error before switching to the trippi-sparql connector, which is why I decided to ask the question. 

Looking through it, here is what I think is the problem. Tear holes in it as you see fit.

You generate a ConfigurableSessionPool of a [max 6 connections](https://github.com/Smithsonian/trippi-sparql/blob/d83c5872d66e8aaed1408e6a624bf3dfe7b7d1a5/trippi-sparql/src/main/java/edu/si/trippi/impl/sparql/SparqlConnector.java#L189)

As all of Islandora is fed through the `/fedora/risearch` interface this would use the triplestore connector, including for stuff that is just a query.

The old config set that [max growth to `-1`](https://github.com/fcrepo3/trippi/blob/5df827690cab0fa1fa98294a35c916de8733d40a/trippi-core/src/main/java/org/trippi/impl/base/ConfigurableSessionPool.java#L59) in `fedora.fcfg` and I am guessing that is the max connections I am seeing used up.

**Comment by ajs6f** [comment]
I think you may have hit the nail on the head. Can you try a patch yourself, or would like me to push a branch with that setting made configurable?

**Comment by whikloj** [comment]
I will try a patch allowing for the same configuration settings as in the old Mulgara connector.

I will say I moved my Solr indexer to query Blazegraph directly instead of using the `/risearch` endpoint and I have seen an improvement in speed as well as no redelivery messages. Watching the Fedora log right now and it appears that 6 ConcurrentTriplestoreWriters could be enough. 

That being the case for me, probably good to have the configuration option available.

**Comment by ajs6f** [comment]
Mos def you want to go against the underlying endpoint directly if you can. The reason I added in the code to pipe queries through `/risearch` is simply because DGI blocked my work to make the query endpoint configurable in Islandora.

**Comment by ajs6f** [comment]
I will send in a PR making this setting configurable. Nice catch, @whikloj -- I don't know why I hard coded that.

**Comment by ajs6f** [comment]
https://github.com/Smithsonian/trippi-sparql/pull/10

**Comment by whikloj** [comment]
I'm gonna close this, as the cause of my error was 60% my fault. But this will definitely help people to avoid the error I was getting and I am now running this build.
👍

**Comment by ajs6f** [comment]
Rad. @ddavis will be cutting a release at some near date to include this.
